language: dart
dart:
  - dev

# Do not remove without verifying w/ Travis.
sudo: required

# Build stages: https://docs.travis-ci.com/user/build-stages/.
stages:
  - presubmit

# 1. Run dartfmt, dartanalyzer.
jobs:
  include:
    # presubmit: Check things that should fail fast(er).
    - stage: presubmit
      env: SHARD=dartfmt
      script: dartfmt -n --set-exit-if-changed . || EXIT_CODE=$?

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

# Incremental pub cache and builds.
cache:
  directories:
    - $HOME/.pub-cache
