name: bio
description: Dart Package for Bioinformatics.
version: 0.0.1
homepage: https://github.com/yech1990/biodart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.3
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
