name: Build on Push

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: bio
            release-name: bio-linux
          - os: macOS-latest
            output-name: bio
            release-name: bio-mac
          - os: windows-latest
            output-name: bio.exe
            release-name: bio-win
    steps:
      - name: Checkout code
        uses: actions/checkout@master

     # Install OS specific dependencies
     - name: Install macOS dependencies
       if: matrix.os == 'macOS-latest'
       run: brew p7zip

      - name: Prepare dart env
        uses: DanTup/gh-actions/setup-dart@master

      - name: Build binary
        run: |
          pub get
          mkdir build
          dart2native bin/main.dart -v -o build/${{ matrix.output-name }}
          mkdir release
          7z release/${{ matrix.release-name }}.7z build/${{ matrix.output-name }}

      - name: Create Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: release/*
          tags: true
          draft: false
