name: Build on Push

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: linux/bio
          - os: macOS-latest
            output-name: macOS/bio
          - os: windows-latest
            output-name: windows/bio.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Prepare dart env
        uses: DanTup/gh-actions/setup-dart@master

      - name: Build binary
        run: |
          pub get
          mkdir build
          dart2native bin/main.dart -v -o build/${{ matrix.output-name }}
          mkdir release
          tar zcvf bio-${{ env.RELEASE_VERSION }}-linux.tar.gz build/linux/bio
          zip bio-${{ env.RELEASE_VERSION }}-macOS.tar.gz build/macOS/bio
          zip bio-${{ env.RELEASE_VERSION }}-windows.tar.gz build/windows/bio.exe


      - name: Create Release
        uses: xresloader/upload-to-github-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/*
          tags: true
          draft: false
